### ISSUE TITLE
Trigger Sirene/Alarm by API

### ISSUE THREAD

**Issue by tomp1k** [c-soft/satel_integra#27]
Hi,

thank you for the excelent python wrapper.

I was wondering if it is possible to trigger (turn on) sirene/alarm by calling API function? 
I have a few non-satel door sensors and I would like to trigger Satel Alarm when these sensors are activated.

Thank you very much for any help.

Tomas

**Comment by pawelgarbacz** [comment]
Yes, but in order to do that you would need an extra monostable input with timer eg for 1 sec or zone (virtual) programmed. It must be set as another input triggering the alarm next to your current inputs/sensors and when you want to pass the alarm trigger an external app like Home Assistant would just need to set this input to on causing the acoustic alarm.
